Assignment2: ApplicationTest.cpp File Reference
ApplicationTest.cpp File Reference
Comprehensive full-pipeline integration tests — Tests 1-25.
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <cmath>
#include "WeatherRecord.h"
#include "WeatherDataStore.h"
#include "DataLoader.h"
#include "DataFileManager.h"
#include "Calculator.h"
#include "OutputHandler.h"
#include "Vector.h"
#include "Date.h"
#include "Time.h"
#include "Constants.h"
#include "Bst.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static void printYearHelper (int &yr)
static void writeCSV (const std::string &path, const std::string &content)
static std::string fileRead (const std::string &path)
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
static void test9 ()
static void test10 ()
static void test11 ()
static void test12 ()
static void test13 ()
static void test14 ()
static void test15 ()
static void test16 ()
static void test17 ()
static void test18 ()
static void test19 ()
static void test20 ()
static void test21 ()
static void test22 ()
static void test23 ()
static void test24 ()
static void test25 ()
int main ()
Variables
static int passed = 0
static int failed = 0
static const float EPS = 0.005f
Detailed Description
Comprehensive full-pipeline integration tests — Tests 1-25.
Tests the complete path from CSV file I/O through DataLoader, DataFileManager (with Bst<long long> duplicate detection), WeatherDataStore::Build, Calculator statistics, and OutputHandler formatting. Every expected numeric value is manually derived below.
Author
Deston
Date
25/03/2026
Definition in file ApplicationTest.cpp.
Function Documentation
fileRead()
static std::string fileRead (const std::string & path) static
Definition at line 59 of file ApplicationTest.cpp.
Referenced by test10(), test11(), and test9().
main()
int main ()
Definition at line 641 of file ApplicationTest.cpp.
References failed, passed, test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test20(), test21(), test22(), test23(), test24(), test25(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
makeRecord()
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp) static
Definition at line 67 of file ApplicationTest.cpp.
References WeatherRecord::SetDate(), WeatherRecord::SetSolarRadiation(), WeatherRecord::SetTemperature(), WeatherRecord::SetTime(), and WeatherRecord::SetWindSpeed().
Referenced by test12(), test13(), test14(), test15(), test2(), test20(), test23(), test24(), test3(), test4(), test5(), test6(), test7(), and test9().
printYearHelper()
static void printYearHelper (int & yr) static
Definition at line 47 of file ApplicationTest.cpp.
Referenced by test20().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 38 of file ApplicationTest.cpp.
References failed, and passed.
Referenced by test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test20(), test21(), test22(), test23(), test24(), test25(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
test1()
static void test1 () static
Definition at line 84 of file ApplicationTest.cpp.
References Vector< T >::Append(), DataFileManager::GetDuplicateCount(), DataFileManager::GetFilesLoaded(), DataFileManager::LoadDataFiles(), report(), and writeCSV().
Referenced by main().
test10()
static void test10 () static
Definition at line 288 of file ApplicationTest.cpp.
References fileRead(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVRow().
Referenced by main().
test11()
static void test11 () static
Definition at line 310 of file ApplicationTest.cpp.
References fileRead(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVNoData().
Referenced by main().
test12()
static void test12 () static
Definition at line 330 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateSolarTotal(), EPS, makeRecord(), and report().
Referenced by main().
test13()
static void test13 () static
Definition at line 353 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateSolarTotal(), EPS, makeRecord(), and report().
Referenced by main().
test14()
static void test14 () static
Definition at line 369 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateWindStats(), EPS, makeRecord(), and report().
Referenced by main().
test15()
static void test15 () static
Definition at line 385 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateTempStats(), EPS, makeRecord(), and report().
Referenced by main().
test16()
static void test16 () static
Definition at line 405 of file ApplicationTest.cpp.
References DataLoader::LoadFromFile(), report(), Vector< T >::Size(), and writeCSV().
Referenced by main().
test17()
static void test17 () static
Definition at line 428 of file ApplicationTest.cpp.
References EPS, DataLoader::LoadFromFile(), report(), Vector< T >::Size(), and writeCSV().
Referenced by main().
test18()
static void test18 () static
Definition at line 452 of file ApplicationTest.cpp.
References Vector< T >::Append(), DataFileManager::GetDuplicateCount(), DataFileManager::LoadDataFiles(), report(), and writeCSV().
Referenced by main().
test19()
static void test19 () static
Definition at line 478 of file ApplicationTest.cpp.
References Vector< T >::Append(), DataFileManager::GetDuplicateCount(), DataFileManager::LoadDataFiles(), report(), and writeCSV().
Referenced by main().
test2()
static void test2 () static
Definition at line 120 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateWindStats(), EPS, makeRecord(), and report().
Referenced by main().
test20()
static void test20 () static
Definition at line 502 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), makeRecord(), printYearHelper(), report(), and WeatherDataStore::TraverseYears().
Referenced by main().
test21()
static void test21 () static
Definition at line 531 of file ApplicationTest.cpp.
References DataLoader::GetLastError(), DataLoader::LoadFromFile(), and report().
Referenced by main().
test22()
static void test22 () static
Definition at line 543 of file ApplicationTest.cpp.
References DataFileManager::ReadDataSourceFile(), report(), and Vector< T >::Size().
Referenced by main().
test23()
static void test23 () static
Definition at line 558 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateWindStats(), EPS, makeRecord(), and report().
Referenced by main().
test24()
static void test24 () static
Definition at line 581 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateTempStats(), EPS, makeRecord(), and report().
Referenced by main().
test25()
static void test25 () static
Definition at line 613 of file ApplicationTest.cpp.
References Bst< T >::insert(), Bst< T >::isEmpty(), report(), Bst< T >::search(), and Bst< T >::size().
Referenced by main().
test3()
static void test3 () static
Definition at line 140 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateWindStats(), makeRecord(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 157 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateTempStats(), EPS, makeRecord(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 178 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateTempStats(), makeRecord(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 199 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateCorrelations(), EPS, makeRecord(), and report().
Referenced by main().
test7()
static void test7 () static
Definition at line 222 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateCorrelations(), EPS, makeRecord(), and report().
Referenced by main().
test8()
static void test8 () static
Definition at line 241 of file ApplicationTest.cpp.
References Calculator::CalculateCorrelations(), and report().
Referenced by main().
test9()
static void test9 () static
Definition at line 257 of file ApplicationTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateSolarTotal(), Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), fileRead(), makeRecord(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVRow().
Referenced by main().
writeCSV()
static void writeCSV (const std::string & path, const std::string & content) static
Definition at line 53 of file ApplicationTest.cpp.
Referenced by test1(), test16(), test17(), test18(), and test19().
Variable Documentation
EPS
const float EPS = 0.005f static
Definition at line 36 of file ApplicationTest.cpp.
Referenced by test12(), test13(), test14(), test15(), test17(), test2(), test23(), test24(), test4(), test6(), and test7().
failed
int failed = 0 static
Definition at line 33 of file ApplicationTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 32 of file ApplicationTest.cpp.
Referenced by main(), and report().