Assignment2: BstTest.cpp File Reference
BstTest.cpp File Reference
Comprehensive unit tests for Bst<T> — Test Plan tests 1-19.
#include <iostream>
#include <string>
#include <sstream>
#include "Bst.h"
#include "Vector.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static void collect (int &v)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
static void test9 ()
static void test10 ()
static void test11 ()
static void test12 ()
static void test13 ()
static void test14 ()
static void test15 ()
static void test16 ()
static void test17 ()
static void test18 ()
static void test19 ()
int main ()
Variables
static int passed = 0
static int failed = 0
static Vector< int > g_col
Detailed Description
Comprehensive unit tests for Bst<T> — Test Plan tests 1-19.
Tests every public method in Bst.h: Default constructor, copy constructor, copy assignment, insert (new/duplicate), deleteNode (leaf/one-child/two-children/absent), search (found/not-found/empty), isEmpty (initial/after-deleted), size, inOrderTraversal (empty/ordered), preOrderTraversal, postOrderTraversal, and large ascending-order stress test.
ITERATIVE vs RECURSIVE (Bst.h version 4.0)
insert() — ITERATIVE (pointer loop, no call stack) search() — ITERATIVE (pointer loop, no call stack) destroyTree — ITERATIVE (heap-allocated pointer array stack)
deleteNode, copyTree, all traversal helpers — still RECURSIVE. These are only called on the small year BST (~15 nodes) so recursion depth is never a concern.
Test 19 specifically validates the iterative fix: it inserts 5,000 values in ascending order (producing a completely right-skewed tree) and confirms that insert(), search(), and destroyTree() (triggered by copy-assignment reset) all complete without a stack overflow. The old recursive versions would crash on ~10,000 values on Windows.
Manual verification of all expected traversal orders:
Tree built by inserting 40, 20, 60, 10, 30:
    40
   /  \
 20    60
/  \
10 30
In-order (left, root, right): 10, 20, 30, 40, 60 Pre-order (root, left, right): 40, 20, 10, 30, 60 Post-order (left, right, root): 10, 30, 20, 60, 40
deleteNode two-children (delete 20 from tree above): In-order successor = 30 (smallest in right subtree of 20). 20 replaced with 30; 30 removed from leaf position. Remaining in-order: 10, 30, 40, 60
deleteNode one-child (delete 70 from {50,30,70,60}): 70 has only left child 60; 60 slides up. Remaining in-order: 30, 50, 60
Copy constructor independence: copy {5,3,7}, insert 4 into copy only. Original in-order: 3, 5, 7 Copy in-order: 3, 4, 5, 7
Author
Deston
Date
24/03/2026
Definition in file BstTest.cpp.
Function Documentation
collect()
static void collect (int & v) static
Definition at line 77 of file BstTest.cpp.
References Vector< T >::Append(), and g_col.
Referenced by test11(), test12(), test16(), test17(), test18(), test6(), test7(), test8(), and test9().
main()
int main ()
Definition at line 438 of file BstTest.cpp.
References failed, passed, test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 68 of file BstTest.cpp.
References failed, and passed.
Referenced by test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
test1()
static void test1 () static
Definition at line 82 of file BstTest.cpp.
References Bst< T >::isEmpty(), report(), and Bst< T >::size().
Referenced by main().
test10()
static void test10 () static
Definition at line 214 of file BstTest.cpp.
References Bst< T >::deleteNode(), Bst< T >::insert(), Bst< T >::isEmpty(), report(), and Bst< T >::search().
Referenced by main().
test11()
static void test11 () static
Definition at line 228 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), Bst< T >::deleteNode(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), Bst< T >::search(), Vector< T >::Size(), and Bst< T >::size().
Referenced by main().
test12()
static void test12 () static
Definition at line 253 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), Bst< T >::deleteNode(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), Bst< T >::search(), Vector< T >::Size(), and Bst< T >::size().
Referenced by main().
test13()
static void test13 () static
Definition at line 277 of file BstTest.cpp.
References Bst< T >::deleteNode(), Bst< T >::insert(), report(), Bst< T >::search(), and Bst< T >::size().
Referenced by main().
test14()
static void test14 () static
Definition at line 295 of file BstTest.cpp.
References Bst< T >::deleteNode(), Bst< T >::insert(), Bst< T >::isEmpty(), report(), and Bst< T >::size().
Referenced by main().
test15()
static void test15 () static
Definition at line 307 of file BstTest.cpp.
References Bst< T >::insert(), report(), and Bst< T >::size().
Referenced by main().
test16()
static void test16 () static
Definition at line 322 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), and Vector< T >::Size().
Referenced by main().
test17()
static void test17 () static
Definition at line 344 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), and Vector< T >::Size().
Referenced by main().
test18()
static void test18 () static
Definition at line 376 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), Bst< T >::search(), and Vector< T >::Size().
Referenced by main().
test19()
static void test19 () static
Definition at line 410 of file BstTest.cpp.
References Bst< T >::insert(), Bst< T >::isEmpty(), report(), Bst< T >::search(), and Bst< T >::size().
Referenced by main().
test2()
static void test2 () static
Definition at line 92 of file BstTest.cpp.
References Bst< T >::insert(), report(), Bst< T >::search(), and Bst< T >::size().
Referenced by main().
test3()
static void test3 () static
Definition at line 103 of file BstTest.cpp.
References Bst< T >::insert(), report(), and Bst< T >::size().
Referenced by main().
test4()
static void test4 () static
Definition at line 115 of file BstTest.cpp.
References Bst< T >::insert(), report(), and Bst< T >::search().
Referenced by main().
test5()
static void test5 () static
Definition at line 126 of file BstTest.cpp.
References report(), and Bst< T >::search().
Referenced by main().
test6()
static void test6 () static
Definition at line 137 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::inOrderTraversal(), Bst< T >::insert(), report(), and Vector< T >::Size().
Referenced by main().
test7()
static void test7 () static
Definition at line 155 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::inOrderTraversal(), report(), and Vector< T >::Size().
Referenced by main().
test8()
static void test8 () static
Definition at line 170 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::insert(), Bst< T >::preOrderTraversal(), report(), and Vector< T >::Size().
Referenced by main().
test9()
static void test9 () static
Definition at line 193 of file BstTest.cpp.
References Vector< T >::Clear(), collect(), g_col, Bst< T >::insert(), Bst< T >::postOrderTraversal(), report(), and Vector< T >::Size().
Referenced by main().
Variable Documentation
failed
int failed = 0 static
Definition at line 66 of file BstTest.cpp.
Referenced by main(), and report().
g_col
Vector<int> g_col static
Definition at line 76 of file BstTest.cpp.
Referenced by collect(), test11(), test12(), test16(), test17(), test18(), test6(), test7(), test8(), and test9().
passed
int passed = 0 static
Definition at line 65 of file BstTest.cpp.
Referenced by main(), and report().