Assignment2: CalculatorTest.cpp File Reference
CalculatorTest.cpp File Reference
Unit tests for Calculator (Assignment 2) — Test Plan tests 1-6.
#include <iostream>
#include <string>
#include <cmath>
#include "Calculator.h"
#include "WeatherDataStore.h"
#include "WeatherRecord.h"
#include "Date.h"
#include "Time.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
int main ()
Variables
static int passed = 0
static int failed = 0
static const float EPS = 0.01f
Detailed Description
Unit tests for Calculator (Assignment 2) — Test Plan tests 1-6.
Tests cover: CalculateWindStats with MAD, empty-store guards, CalculateTempStats with MAD, CalculateSolarTotal threshold, CalculateCorrelations empty guard, and CalculateCorrelations S_T near 1.0.
Author
Deston
Date
24/03/2026
Definition in file CalculatorTest.cpp.
Function Documentation
main()
int main ()
Definition at line 128 of file CalculatorTest.cpp.
References failed, passed, test1(), test2(), test3(), test4(), test5(), and test6().
makeRecord()
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp) static
Definition at line 33 of file CalculatorTest.cpp.
References WeatherRecord::SetDate(), WeatherRecord::SetSolarRadiation(), WeatherRecord::SetTemperature(), WeatherRecord::SetTime(), and WeatherRecord::SetWindSpeed().
Referenced by test1(), test3(), test4(), and test6().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 26 of file CalculatorTest.cpp.
References failed, and passed.
Referenced by test1(), test2(), test3(), test4(), test5(), and test6().
test1()
static void test1 () static
Definition at line 46 of file CalculatorTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateWindStats(), EPS, makeRecord(), and report().
Referenced by main().
test2()
static void test2 () static
Definition at line 63 of file CalculatorTest.cpp.
References Calculator::CalculateWindStats(), and report().
Referenced by main().
test3()
static void test3 () static
Definition at line 73 of file CalculatorTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateTempStats(), EPS, makeRecord(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 88 of file CalculatorTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateSolarTotal(), EPS, makeRecord(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 103 of file CalculatorTest.cpp.
References Calculator::CalculateCorrelations(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 113 of file CalculatorTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Calculator::CalculateCorrelations(), EPS, makeRecord(), and report().
Referenced by main().
Variable Documentation
EPS
const float EPS = 0.01f static
Definition at line 24 of file CalculatorTest.cpp.
Referenced by test1(), test3(), test4(), and test6().
failed
int failed = 0 static
Definition at line 23 of file CalculatorTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 22 of file CalculatorTest.cpp.
Referenced by main(), and report().