Assignment2: WeatherRecord Class Reference
WeatherRecord Class Reference
#include <WeatherRecord.h>
Public Member Functions
WeatherRecord ()
Default constructor — initialises all numeric fields to 0.
Date GetDate () const
Get the date of the reading.
void SetDate (const Date &d)
Set the date of the reading.
Time GetTime () const
Get the time of the reading.
void SetTime (const Time &t)
Set the time of the reading.
float GetWindSpeed () const
Get wind speed in m/s.
void SetWindSpeed (float speed)
Set wind speed in m/s.
float GetSolarRadiation () const
Get solar radiation in W/m2.
void SetSolarRadiation (float radiation)
Set solar radiation in W/m2.
float GetTemperature () const
Get temperature in degrees C.
void SetTemperature (float temp)
Set temperature in degrees C.
int GetYear () const
Get the year of the reading.
bool MatchesMonthYear (int month, int year) const
Check whether this record belongs to a given month and year.
Private Attributes
Date m_date
Time m_time
float m_windSpeed
float m_solarRadiation
float m_temperature
Detailed Description
Definition at line 22 of file WeatherRecord.h.
Constructor & Destructor Documentation
WeatherRecord()
WeatherRecord::WeatherRecord ()
Default constructor — initialises all numeric fields to 0.
Definition at line 3 of file WeatherRecord.cpp.
Member Function Documentation
GetDate()
Date WeatherRecord::GetDate () const
Get the date of the reading.
Definition at line 8 of file WeatherRecord.cpp.
References m_date.
Referenced by WeatherDataStore::Build(), and DataFileManager::MakeTimestampKey().
GetSolarRadiation()
float WeatherRecord::GetSolarRadiation () const
Get solar radiation in W/m2.
Definition at line 38 of file WeatherRecord.cpp.
References m_solarRadiation.
Referenced by WeatherDataStore::Build().
GetTemperature()
float WeatherRecord::GetTemperature () const
Get temperature in degrees C.
Definition at line 48 of file WeatherRecord.cpp.
References m_temperature.
Referenced by WeatherDataStore::Build().
GetTime()
Time WeatherRecord::GetTime () const
Get the time of the reading.
Definition at line 18 of file WeatherRecord.cpp.
References m_time.
Referenced by DataFileManager::MakeTimestampKey().
GetWindSpeed()
float WeatherRecord::GetWindSpeed () const
Get wind speed in m/s.
Definition at line 28 of file WeatherRecord.cpp.
References m_windSpeed.
Referenced by WeatherDataStore::Build().
GetYear()
int WeatherRecord::GetYear () const
Get the year of the reading.
Returns
Year component of the record's date
Definition at line 58 of file WeatherRecord.cpp.
References Date::GetYear(), and m_date.
MatchesMonthYear()
bool WeatherRecord::MatchesMonthYear (int month, int year) const
Check whether this record belongs to a given month and year.
Parameters
month Month number (1-12)
year Year
Returns
true if the record's date matches both month and year
Definition at line 63 of file WeatherRecord.cpp.
References Date::GetMonth(), Date::GetYear(), and m_date.
SetDate()
void WeatherRecord::SetDate (const Date & d)
Set the date of the reading.
Definition at line 13 of file WeatherRecord.cpp.
References m_date.
Referenced by buildStoreWithYears(), makeRecord(), and DataLoader::ParseLine().
SetSolarRadiation()
void WeatherRecord::SetSolarRadiation (float radiation)
Set solar radiation in W/m2.
Definition at line 43 of file WeatherRecord.cpp.
References m_solarRadiation.
Referenced by buildStoreWithYears(), makeRecord(), and DataLoader::ParseLine().
SetTemperature()
void WeatherRecord::SetTemperature (float temp)
Set temperature in degrees C.
Definition at line 53 of file WeatherRecord.cpp.
References m_temperature.
Referenced by buildStoreWithYears(), makeRecord(), and DataLoader::ParseLine().
SetTime()
void WeatherRecord::SetTime (const Time & t)
Set the time of the reading.
Definition at line 23 of file WeatherRecord.cpp.
References m_time.
Referenced by buildStoreWithYears(), makeRecord(), and DataLoader::ParseLine().
SetWindSpeed()
void WeatherRecord::SetWindSpeed (float speed)
Set wind speed in m/s.
Definition at line 33 of file WeatherRecord.cpp.
References m_windSpeed.
Referenced by buildStoreWithYears(), makeRecord(), and DataLoader::ParseLine().
Member Data Documentation
m_date
Date WeatherRecord::m_date private
Date of reading
Definition at line 75 of file WeatherRecord.h.
Referenced by GetDate(), GetYear(), MatchesMonthYear(), and SetDate().
m_solarRadiation
float WeatherRecord::m_solarRadiation private
Solar radiation in W/m2
Definition at line 78 of file WeatherRecord.h.
Referenced by GetSolarRadiation(), and SetSolarRadiation().
m_temperature
float WeatherRecord::m_temperature private
Temperature in degrees C
Definition at line 79 of file WeatherRecord.h.
Referenced by GetTemperature(), and SetTemperature().
m_time
Time WeatherRecord::m_time private
Time of reading
Definition at line 76 of file WeatherRecord.h.
Referenced by GetTime(), and SetTime().
m_windSpeed
float WeatherRecord::m_windSpeed private
Wind speed in m/s
Definition at line 77 of file WeatherRecord.h.
Referenced by GetWindSpeed(), and SetWindSpeed().
The documentation for this class was generated from the following files:
WeatherRecord.h
WeatherRecord.cpp