Assignment2: OutputHandler Class Reference
OutputHandler Class Reference
#include <OutputHandler.h>
Public Member Functions
OutputHandler ()
Default constructor.
void DisplayWindStats (int month, int year, float mean, float stdDev) const
Display wind speed statistics for a single month/year (option 1).
void DisplayNoData (int month, int year) const
Display a no-data message for a month/year (option 1).
void DisplayTempHeader (int year) const
Display the temperature section year header (option 2).
void DisplayTempForMonth (int month, float mean, float stdDev) const
Display temperature statistics for one month (option 2).
void DisplayNoDataForMonth (int month) const
Display a no-data message for one month in a multi-month listing.
void DisplaySPCCHeader (int month) const
Display the sPCC section header showing the selected month (option 3).
void DisplaySPCC (float s_t, float s_r, float t_r) const
Display the three sPCC values: S_T, S_R, T_R (option 3).
void DisplaySPCCNoData (int month) const
Display a no-data message when sPCC cannot be computed (option 3).
void WriteCSVHeader (std::ofstream &file, int year) const
Write the year header line to an open CSV file (option 4).
void WriteCSVRow (std::ofstream &file, int month, bool hasWind, float windMean, float windStdDev, float windMAD, bool hasTemp, float tempMean, float tempStdDev, float tempMAD, bool hasSolar, float solarTotal) const
Write one month data row to the CSV file with stdev AND MAD (option 4).
void WriteCSVNoData (std::ofstream &file) const
Write "No Data" to the CSV file when an entire year has no records.
void DisplayFileWritten (const std::string &filename) const
Display confirmation that the CSV file was written successfully.
void DisplayFileError (const std::string &filename) const
Display an error message when the CSV file cannot be opened.
Static Private Member Functions
static std::string GetMonthName (int month)
Convert a month number to its full name.
Detailed Description
Definition at line 19 of file OutputHandler.h.
Constructor & Destructor Documentation
OutputHandler()
OutputHandler::OutputHandler ()
Default constructor.
Definition at line 12 of file OutputHandler.cpp.
Member Function Documentation
DisplayFileError()
void OutputHandler::DisplayFileError (const std::string & filename) const
Display an error message when the CSV file cannot be opened.
Parameters
filename Path of the file that could not be opened.
Definition at line 146 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption4().
DisplayFileWritten()
void OutputHandler::DisplayFileWritten (const std::string & filename) const
Display confirmation that the CSV file was written successfully.
Parameters
filename Path of the written file.
Definition at line 140 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption4().
DisplayNoData()
void OutputHandler::DisplayNoData (int month, int year) const
Display a no-data message for a month/year (option 1).
Parameters
month Month number (1-12).
year Calendar year.
Definition at line 43 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption1(), and test2().
DisplayNoDataForMonth()
void OutputHandler::DisplayNoDataForMonth (int month) const
Display a no-data message for one month in a multi-month listing.
Parameters
month Month number (1-12).
Definition at line 67 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption2(), and test5().
DisplaySPCC()
void OutputHandler::DisplaySPCC (float s_t, float s_r, float t_r) const
Display the three sPCC values: S_T, S_R, T_R (option 3).
Parameters
s_t sPCC for Wind Speed vs Temperature.
s_r sPCC for Wind Speed vs Solar Radiation.
t_r sPCC for Temperature vs Solar Radiation.
Definition at line 83 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption3(), and test7().
DisplaySPCCHeader()
void OutputHandler::DisplaySPCCHeader (int month) const
Display the sPCC section header showing the selected month (option 3).
Parameters
month Month number (1-12).
Definition at line 76 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption3(), and test6().
DisplaySPCCNoData()
void OutputHandler::DisplaySPCCNoData (int month) const
Display a no-data message when sPCC cannot be computed (option 3).
Parameters
month Month number (1-12).
Definition at line 92 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption3(), and test8().
DisplayTempForMonth()
void OutputHandler::DisplayTempForMonth (int month, float mean, float stdDev) const
Display temperature statistics for one month (option 2).
Parameters
month Month number (1-12).
mean Mean temperature in degrees C.
stdDev Sample standard deviation in degrees C.
Definition at line 59 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption2(), and test4().
DisplayTempHeader()
void OutputHandler::DisplayTempHeader (int year) const
Display the temperature section year header (option 2).
Parameters
year Year being reported.
Definition at line 53 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption2(), and test3().
DisplayWindStats()
void OutputHandler::DisplayWindStats (int month, int year, float mean, float stdDev) const
Display wind speed statistics for a single month/year (option 1).
Parameters
month Month number (1-12).
year Calendar year.
mean Mean wind speed in km/h.
stdDev Sample standard deviation in km/h.
Definition at line 33 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption1(), and test1().
GetMonthName()
std::string OutputHandler::GetMonthName (int month) static private
Convert a month number to its full name.
Parameters
month Month number (1-12).
Returns
Full month name (e.g. "March"), or "Unknown" for invalid input.
Definition at line 16 of file OutputHandler.cpp.
Referenced by DisplayNoData(), DisplayNoDataForMonth(), DisplaySPCCHeader(), DisplaySPCCNoData(), DisplayTempForMonth(), DisplayWindStats(), and WriteCSVRow().
WriteCSVHeader()
void OutputHandler::WriteCSVHeader (std::ofstream & file, int year) const
Write the year header line to an open CSV file (option 4).
Parameters
file Open output stream.
year Year being reported.
Definition at line 102 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption4(), test10(), test11(), test12(), and test9().
WriteCSVNoData()
void OutputHandler::WriteCSVNoData (std::ofstream & file) const
Write "No Data" to the CSV file when an entire year has no records.
Parameters
file Open output stream.
Definition at line 133 of file OutputHandler.cpp.
Referenced by MenuHandler::HandleOption4(), test11(), and test12().
WriteCSVRow()
void OutputHandler::WriteCSVRow (std::ofstream & file, int month, bool hasWind, float windMean, float windStdDev, float windMAD, bool hasTemp, float tempMean, float tempStdDev, float tempMAD, bool hasSolar, float solarTotal) const
Write one month data row to the CSV file with stdev AND MAD (option 4).
Output format per A2 spec: MonthName, windMean(windStdDev, windMAD),tempMean(tempStdDev, tempMAD),solar
If a field has no data (hasWind/hasTemp/hasSolar = false) the field is left blank between its surrounding commas, e.g.: February, 4.5(3.1, 2.9),,200.3
Parameters
file Open output stream.
month Month number (1-12).
hasWind true if wind data is valid.
windMean Mean wind speed in km/h.
windStdDev Wind sample standard deviation.
windMAD Wind mean absolute deviation.
hasTemp true if temperature data is valid.
tempMean Mean temperature in degrees C.
tempStdDev Temperature sample standard deviation.
tempMAD Temperature mean absolute deviation.
hasSolar true if solar data is valid.
solarTotal Total solar radiation in kWh/m2.
Definition at line 107 of file OutputHandler.cpp.
References GetMonthName().
Referenced by MenuHandler::HandleOption4(), test10(), test11(), and test9().
The documentation for this class was generated from the following files:
OutputHandler.h
OutputHandler.cpp