Assignment2: WeatherDataStore Class Reference
WeatherDataStore Class Reference
#include <WeatherDataStore.h>
Public Member Functions
WeatherDataStore ()
Default constructor — creates an empty store.
void Build (const Vector< WeatherRecord > &records)
Populate the store from a flat Vector of WeatherRecord.
bool HasData (int year, int month) const
Check whether data exists for a given year and month.
const MonthlyData * GetMonthData (int year, int month) const
Const pointer to the MonthlyData for a specific year and month.
void GetMonthDataAllYears (int month, Vector< float > &winds, Vector< float > &temps, Vector< float > &solarRaw) const
Collect parallel wind/temperature/solarRaw vectors for one month across ALL loaded years (used for sPCC in option 3).
void TraverseYears (void(*visit)(int &)) const
In-order traversal of the year BST using the f1Typ callback.
bool YearExists (int year) const
Check whether a year exists in the BST.
int GetYearCount () const
Number of unique years stored in the BST.
bool IsEmpty () const
Check whether the store is completely empty.
Static Private Member Functions
static float ToKmh (float mps)
Convert wind speed from m/s to km/h.
Private Attributes
Map< int, Map< int, MonthlyData > > m_data
Nested Map: year -> month -> MonthlyData vectors.
Bst< int > m_yearBst
BST of unique years — sorted traversal and O(log n) search.
Detailed Description
Definition at line 67 of file WeatherDataStore.h.
Constructor & Destructor Documentation
WeatherDataStore()
WeatherDataStore::WeatherDataStore ()
Default constructor — creates an empty store.
Definition at line 3 of file WeatherDataStore.cpp.
Member Function Documentation
Build()
void WeatherDataStore::Build (const Vector< WeatherRecord > & records)
Populate the store from a flat Vector of WeatherRecord.
Iterates once through all records. Each record is inserted into Map[year][month] (created automatically via operator[] if absent) and the year is inserted into the BST (duplicates silently ignored). Wind speed is converted from m/s to km/h during insertion.
Parameters
records All loaded weather records.
Definition at line 13 of file WeatherDataStore.cpp.
References Vector< T >::Append(), WeatherRecord::GetDate(), Date::GetMonth(), WeatherRecord::GetSolarRadiation(), WeatherRecord::GetTemperature(), WeatherRecord::GetWindSpeed(), Date::GetYear(), Bst< T >::insert(), m_data, m_yearBst, Vector< T >::Size(), MonthlyData::solarRaw, MonthlyData::temperatures, ToKmh(), and MonthlyData::windSpeeds.
Referenced by buildStoreWithYears(), main(), test1(), test12(), test13(), test14(), test15(), test2(), test20(), test23(), test24(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
GetMonthData()
const MonthlyData * WeatherDataStore::GetMonthData (int year, int month) const
Const pointer to the MonthlyData for a specific year and month.
Parameters
year Calendar year.
month Month number (1-12).
Returns
Pointer to MonthlyData, or nullptr if no data exists.
Definition at line 43 of file WeatherDataStore.cpp.
References Map< K, V >::getPtr(), and m_data.
Referenced by Calculator::CalculateSolarTotal(), Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), test5(), and test8().
GetMonthDataAllYears()
void WeatherDataStore::GetMonthDataAllYears (int month, Vector< float > & winds, Vector< float > & temps, Vector< float > & solarRaw) const
Collect parallel wind/temperature/solarRaw vectors for one month across ALL loaded years (used for sPCC in option 3).
Iterates the outer Map by index to visit every year, then checks whether that year's inner Map contains the requested month.
Parameters
month Month number (1-12).
winds Output: wind speeds (km/h) across all years.
temps Output: temperatures (C) across all years.
solarRaw Output: raw solar radiation (W/m2) across all years.
Definition at line 51 of file WeatherDataStore.cpp.
References Vector< T >::Append(), Map< K, V >::getKey(), Map< K, V >::getPtr(), m_data, Map< K, V >::size(), Vector< T >::Size(), MonthlyData::solarRaw, MonthlyData::temperatures, and MonthlyData::windSpeeds.
Referenced by Calculator::CalculateCorrelations(), and test6().
GetYearCount()
int WeatherDataStore::GetYearCount () const
Number of unique years stored in the BST.
Returns
Count of unique years.
Definition at line 84 of file WeatherDataStore.cpp.
References m_yearBst, and Bst< T >::size().
Referenced by test2().
HasData()
bool WeatherDataStore::HasData (int year, int month) const
Check whether data exists for a given year and month.
Parameters
year Calendar year.
month Month number (1-12).
Returns
true if at least one reading was stored for that year/month.
Definition at line 33 of file WeatherDataStore.cpp.
References Map< K, V >::getPtr(), and m_data.
Referenced by test3(), and test4().
IsEmpty()
bool WeatherDataStore::IsEmpty () const
Check whether the store is completely empty.
Returns
true if no records have been built into the store.
Definition at line 89 of file WeatherDataStore.cpp.
References Bst< T >::isEmpty(), and m_yearBst.
Referenced by main(), and test1().
ToKmh()
float WeatherDataStore::ToKmh (float mps) static private
Convert wind speed from m/s to km/h.
Parameters
mps Speed in metres per second.
Returns
Speed in kilometres per hour (mps * WIND_MPS_TO_KMH).
Definition at line 8 of file WeatherDataStore.cpp.
References WIND_MPS_TO_KMH.
Referenced by Build().
TraverseYears()
void WeatherDataStore::TraverseYears (void(*)(int &) visit) const
In-order traversal of the year BST using the f1Typ callback.
Passes the caller-supplied function pointer directly to Bst<int>::inOrderTraversal, which visits each year in ascending order and invokes the callback
Parameters
visit Callback matching Bst<int>::f1Typ: void (*)(int&).
Definition at line 74 of file WeatherDataStore.cpp.
References Bst< T >::inOrderTraversal(), and m_yearBst.
Referenced by MenuHandler::DisplayAvailableYears(), test20(), and test7().
YearExists()
bool WeatherDataStore::YearExists (int year) const
Check whether a year exists in the BST.
Parameters
year Year to look up.
Returns
true if the year was loaded.
Definition at line 79 of file WeatherDataStore.cpp.
References m_yearBst, and Bst< T >::search().
Referenced by MenuHandler::GetYearInput(), and test2().
Member Data Documentation
m_data
Map<int, Map<int, MonthlyData> > WeatherDataStore::m_data private
Nested Map: year -> month -> MonthlyData vectors.
Outer Map key: calendar year (int). Inner Map key: month number 1-12 (int). Value: MonthlyData struct with three parallel float Vectors.
Definition at line 158 of file WeatherDataStore.h.
Referenced by Build(), GetMonthData(), GetMonthDataAllYears(), and HasData().
m_yearBst
Bst<int> WeatherDataStore::m_yearBst private
BST of unique years — sorted traversal and O(log n) search.
Definition at line 161 of file WeatherDataStore.h.
Referenced by Build(), GetYearCount(), IsEmpty(), TraverseYears(), and YearExists().
The documentation for this class was generated from the following files:
WeatherDataStore.h
WeatherDataStore.cpp