Assignment2: Calculator Class Reference
Calculator Class Reference
#include <Calculator.h>
Public Member Functions
Calculator ()
Default constructor.
bool CalculateWindStats (const WeatherDataStore &store, int month, int year, float &mean, float &stdDev, float &mad) const
Mean, sample stdev, and MAD of wind speed for one month/year.
bool CalculateTempStats (const WeatherDataStore &store, int month, int year, float &mean, float &stdDev, float &mad) const
Mean, sample stdev, and MAD of temperature for one month/year.
bool CalculateSolarTotal (const WeatherDataStore &store, int month, int year, float &total) const
Total solar radiation for one month/year in kWh/m2.
bool CalculateCorrelations (const WeatherDataStore &store, int month, float &s_t, float &s_r, float &t_r) const
Sample Pearson Correlation Coefficients for a given month across ALL loaded years.
Static Private Member Functions
static float ToKwhM2 (float wm2)
Convert a 10-minute W/m2 solar reading to kWh/m2.
Detailed Description
Definition at line 20 of file Calculator.h.
Constructor & Destructor Documentation
Calculator()
Calculator::Calculator ()
Default constructor.
Definition at line 4 of file Calculator.cpp.
Member Function Documentation
CalculateCorrelations()
bool Calculator::CalculateCorrelations (const WeatherDataStore & store, int month, float & s_t, float & s_r, float & t_r) const
Sample Pearson Correlation Coefficients for a given month across ALL loaded years.
Combinations computed:
S_T: Wind Speed vs Temperature (all records for the month)
S_R: Wind Speed vs Solar Radiation (records where SR >= 100 W/m2 only)
T_R: Temperature vs Solar Radiation (records where SR >= 100 W/m2 only)
Parameters
store Indexed weather data store.
month Month number (1-12).
s_t Output: sPCC for Wind Speed vs Temperature.
s_r Output: sPCC for Wind Speed vs Solar Radiation.
t_r Output: sPCC for Temperature vs Solar Radiation.
Returns
true if enough data existed to compute at least S_T.
Definition at line 60 of file Calculator.cpp.
References Vector< T >::Append(), CalculateSPCC(), WeatherDataStore::GetMonthDataAllYears(), MIN_SOLAR_RADIATION, Vector< T >::Size(), and ToKwhM2().
Referenced by MenuHandler::HandleOption3(), test5(), test6(), test7(), and test8().
CalculateSolarTotal()
bool Calculator::CalculateSolarTotal (const WeatherDataStore & store, int month, int year, float & total) const
Total solar radiation for one month/year in kWh/m2.
Only readings >= MIN_SOLAR_RADIATION W/m2 are included. Conversion: W/m2 over 10 min = W/m2 / 6000 kWh/m2.
Parameters
store Indexed weather data store.
month Month number (1-12).
year Calendar year.
total Output: total solar radiation in kWh/m2.
Returns
true if at least one qualifying reading was found.
Definition at line 39 of file Calculator.cpp.
References WeatherDataStore::GetMonthData(), MIN_SOLAR_RADIATION, Vector< T >::Size(), MonthlyData::solarRaw, and ToKwhM2().
Referenced by MenuHandler::HandleOption4(), test12(), test13(), test4(), and test9().
CalculateTempStats()
bool Calculator::CalculateTempStats (const WeatherDataStore & store, int month, int year, float & mean, float & stdDev, float & mad) const
Mean, sample stdev, and MAD of temperature for one month/year.
Parameters
store Indexed weather data store.
month Month number (1-12).
year Calendar year.
mean Output: mean temperature in degrees C.
stdDev Output: sample standard deviation in degrees C.
mad Output: mean absolute deviation in degrees C.
Returns
true if at least one record was found.
Definition at line 26 of file Calculator.cpp.
References CalculateMAD(), CalculateMean(), CalculateSampleStdDev(), Vector< T >::Empty(), WeatherDataStore::GetMonthData(), and MonthlyData::temperatures.
Referenced by MenuHandler::HandleOption2(), MenuHandler::HandleOption4(), test15(), test24(), test3(), test4(), test5(), and test9().
CalculateWindStats()
bool Calculator::CalculateWindStats (const WeatherDataStore & store, int month, int year, float & mean, float & stdDev, float & mad) const
Mean, sample stdev, and MAD of wind speed for one month/year.
Parameters
store Indexed weather data store.
month Month number (1-12).
year Calendar year.
mean Output: mean wind speed in km/h.
stdDev Output: sample standard deviation in km/h.
mad Output: mean absolute deviation in km/h.
Returns
true if at least one record was found.
Definition at line 13 of file Calculator.cpp.
References CalculateMAD(), CalculateMean(), CalculateSampleStdDev(), Vector< T >::Empty(), WeatherDataStore::GetMonthData(), and MonthlyData::windSpeeds.
Referenced by MenuHandler::HandleOption1(), MenuHandler::HandleOption4(), test1(), test14(), test2(), test23(), test3(), and test9().
ToKwhM2()
float Calculator::ToKwhM2 (float wm2) static private
Convert a 10-minute W/m2 solar reading to kWh/m2.
Parameters
wm2 Solar radiation in W/m2.
Returns
Energy in kWh/m2.
Definition at line 8 of file Calculator.cpp.
References SOLAR_CONVERSION_DIVISOR.
Referenced by CalculateCorrelations(), and CalculateSolarTotal().
The documentation for this class was generated from the following files:
Calculator.h
Calculator.cpp