Assignment2: Vector< T > Class Template Reference
Vector< T > Class Template Reference
#include <Vector.h>
Public Member Functions
Vector ()
Default constructor.
Vector (int n)
Parameterised constructor with initial capacity hint.
~Vector ()
Destructor.
bool Insert (int index, const T &data)
Insert element at the specified index.
bool Delete (int index)
Delete the element at a given index.
const T & operator[] (int index) const
Read-only element access.
T & operator[] (int index)
Read-write element access.
bool Empty () const
Check whether the Vector contains no elements.
int Size () const
Get the current number of stored elements.
int Capacity () const
Get the current allocated capacity.
void Clear ()
Remove all elements from the Vector.
bool Append (const T &data)
Append an element to the end of the Vector.
void Reserve (int n)
Pre-allocate storage for at least n elements.
Private Attributes
vector< T > m_vector
Detailed Description
template<class T>
class Vector< T >
Definition at line 27 of file Vector.h.
Constructor & Destructor Documentation
Vector() [1/2]
template<class T > Vector< T >::Vector () inline
Default constructor.
Initialises an empty Vector with a reserved capacity of 5. This avoids immediate reallocation for the first few appends while keeping the initial memory footprint small.
Definition at line 37 of file Vector.h.
Vector() [2/2]
template<class T > Vector< T >::Vector (int n) explicit
Parameterised constructor with initial capacity hint.
Parameters
n Desired capacity hint; the internal capacity is reserved as n*2. If n <= 0 it defaults to 5 before doubling.
Allows callers to specify expected usage, reducing the number of reallocation events. Size is 0 after construction regardless of n.
Definition at line 147 of file Vector.h.
~Vector()
template<class T > Vector< T >::~Vector () inline
Destructor.
std::vector releases its heap allocation automatically; no manual resource management is required here.
Definition at line 55 of file Vector.h.
Member Function Documentation
Append()
template<class T > bool Vector< T >::Append (const T & data)
Append an element to the end of the Vector.
Parameters
data Element to append
Returns
true always (capacity is grown automatically if needed)
Convenience method equivalent to Insert(Size(), data).
Definition at line 222 of file Vector.h.
Referenced by WeatherDataStore::Build(), buildStoreWithYears(), Calculator::CalculateCorrelations(), collect(), collectYear(), WeatherDataStore::GetMonthDataAllYears(), DataFileManager::LoadDataFiles(), DataLoader::LoadFromFile(), DataFileManager::ReadDataSourceFile(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test18(), test19(), test2(), test20(), test23(), test24(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
Capacity()
template<class T > int Vector< T >::Capacity
Get the current allocated capacity.
Returns
Number of elements the Vector can hold before reallocation
Definition at line 210 of file Vector.h.
Clear()
template<class T > void Vector< T >::Clear
Remove all elements from the Vector.
Sets Size() to 0. The allocated capacity is preserved so that subsequent appends do not immediately trigger reallocation.
Definition at line 216 of file Vector.h.
Referenced by test11(), test12(), test16(), test17(), test18(), test6(), test7(), test8(), and test9().
Delete()
template<class T > bool Vector< T >::Delete (int index)
Delete the element at a given index.
Parameters
index Zero-based position to remove (0 <= index < Size())
Returns
true if deletion succeeded, false if index is out of range
Removes the element at index and shifts all subsequent elements one position to the left.
Definition at line 175 of file Vector.h.
Empty()
template<class T > bool Vector< T >::Empty
Check whether the Vector contains no elements.
Returns
true if Size() == 0, false otherwise
Definition at line 198 of file Vector.h.
Referenced by Calculator::CalculateTempStats(), and Calculator::CalculateWindStats().
Insert()
template<class T > bool Vector< T >::Insert (int index, const T & data)
Insert element at the specified index.
Parameters
index Position to insert (0 to Size(), inclusive)
data Element to insert
Returns
true if the insertion succeeded, false if index is out of range
Elements at and after index are shifted right by one position. Resizing is automatic; callers do not need to request it.
Definition at line 157 of file Vector.h.
operator[]() [1/2]
template<class T > T & Vector< T >::operator[] (int index)
Read-write element access.
Parameters
index Zero-based position to access
Returns
Reference to the element at index
No bounds checking is performed; the caller must supply a valid index.
Definition at line 192 of file Vector.h.
operator[]() [2/2]
template<class T > const T & Vector< T >::operator[] (int index) const
Read-only element access.
Parameters
index Zero-based position to access
Returns
Const reference to the element at index
No bounds checking is performed; the caller must supply a valid index.
Definition at line 186 of file Vector.h.
Reserve()
template<class T > void Vector< T >::Reserve (int n)
Pre-allocate storage for at least n elements.
Parameters
n Minimum capacity to reserve
Avoids repeated reallocation when loading large datasets. Has no effect if n <= Capacity().
Definition at line 229 of file Vector.h.
Size()
template<class T > int Vector< T >::Size
Get the current number of stored elements.
Returns
Number of elements currently in the Vector
Definition at line 204 of file Vector.h.
Referenced by WeatherDataStore::Build(), Calculator::CalculateCorrelations(), CalculateMAD(), CalculateMean(), CalculateSampleStdDev(), Calculator::CalculateSolarTotal(), CalculateSPCC(), WeatherDataStore::GetMonthDataAllYears(), DataFileManager::LoadDataFiles(), main(), test11(), test12(), test16(), test17(), test18(), test22(), test5(), test6(), test7(), test8(), and test9().
Member Data Documentation
m_vector
template<class T > vector<T> Vector< T >::m_vector private
Definition at line 141 of file Vector.h.
The documentation for this class was generated from the following file:
Vector.h