Assignment2: MenuHandler Class Reference
MenuHandler Class Reference
#include <MenuHandler.h>
Public Member Functions
MenuHandler ()
Default constructor.
int DisplayMenu () const
Display the main menu and return the user's choice (1-5).
void DisplayWelcome (int recordCount) const
Display a welcome message with the total record count.
void DisplayAvailableYears (const WeatherDataStore &store) const
Print available years using BST in-order traversal.
void HandleOption1 (const WeatherDataStore &store, const Calculator &calc, const OutputHandler &output) const
Option 1 — wind speed mean and stdev for a user-specified month/year.
void HandleOption2 (const WeatherDataStore &store, const Calculator &calc, const OutputHandler &output) const
Option 2 — temperature statistics for all months of a year.
void HandleOption3 (const WeatherDataStore &store, const Calculator &calc, const OutputHandler &output) const
Option 3 — Sample Pearson Correlation Coefficients (S_T, S_R, T_R) for a user-specified month across ALL loaded years.
void HandleOption4 (const WeatherDataStore &store, const Calculator &calc, const OutputHandler &output) const
Option 4 — write Wind/Temp/Solar CSV with stdev and MAD for a year.
void DisplayGoodbye () const
Display the exit message.
Private Member Functions
int GetIntInput (const std::string &prompt) const
Read and validate an integer from standard input.
int GetMonthInput () const
Prompt for and validate a month number (1-12).
int GetYearInput (const WeatherDataStore &store) const
Prompt for and validate a year that exists in the store.
void ClearInput () const
Discard remaining characters in the input buffer.
Static Private Member Functions
static void PrintYear (int &year)
Static visitor passed to Bst<int>::inOrderTraversal as f1Typ.
Detailed Description
Definition at line 24 of file MenuHandler.h.
Constructor & Destructor Documentation
MenuHandler()
MenuHandler::MenuHandler ()
Default constructor.
Definition at line 9 of file MenuHandler.cpp.
Member Function Documentation
ClearInput()
void MenuHandler::ClearInput () const private
Discard remaining characters in the input buffer.
Definition at line 221 of file MenuHandler.cpp.
Referenced by DisplayMenu(), and GetIntInput().
DisplayAvailableYears()
void MenuHandler::DisplayAvailableYears (const WeatherDataStore & store) const
Print available years using BST in-order traversal.
Calls store.TraverseYears(PrintYear). PrintYear is a static member whose address is a plain function pointer matching Bst<int>::f1Typ. The BST delivers years in ascending order.
Parameters
store Populated weather data store.
Definition at line 56 of file MenuHandler.cpp.
References PrintYear(), and WeatherDataStore::TraverseYears().
Referenced by GetYearInput(), main(), test3(), test4(), test5(), and test7().
DisplayGoodbye()
void MenuHandler::DisplayGoodbye () const
Display the exit message.
Definition at line 171 of file MenuHandler.cpp.
Referenced by main(), and test2().
DisplayMenu()
int MenuHandler::DisplayMenu () const
Display the main menu and return the user's choice (1-5).
Returns
Integer choice entered by the user.
Definition at line 22 of file MenuHandler.cpp.
References ClearInput().
Referenced by main(), and test6().
DisplayWelcome()
void MenuHandler::DisplayWelcome (int recordCount) const
Display a welcome message with the total record count.
Parameters
recordCount Number of records loaded from all files.
Definition at line 49 of file MenuHandler.cpp.
Referenced by main(), and test1().
GetIntInput()
int MenuHandler::GetIntInput (const std::string & prompt) const private
Read and validate an integer from standard input.
Parameters
prompt Text to display before reading.
Returns
Valid integer entered by the user.
Definition at line 181 of file MenuHandler.cpp.
References ClearInput().
Referenced by GetMonthInput(), and GetYearInput().
GetMonthInput()
int MenuHandler::GetMonthInput () const private
Prompt for and validate a month number (1-12).
Returns
Valid month number.
Definition at line 195 of file MenuHandler.cpp.
References GetIntInput().
Referenced by HandleOption1(), and HandleOption3().
GetYearInput()
int MenuHandler::GetYearInput (const WeatherDataStore & store) const private
Prompt for and validate a year that exists in the store.
Parameters
store Used to verify the entered year exists via YearExists().
Returns
Valid year present in the loaded data.
Definition at line 207 of file MenuHandler.cpp.
References DisplayAvailableYears(), GetIntInput(), and WeatherDataStore::YearExists().
Referenced by HandleOption1(), HandleOption2(), and HandleOption4().
HandleOption1()
void MenuHandler::HandleOption1 (const WeatherDataStore & store, const Calculator & calc, const OutputHandler & output) const
Option 1 — wind speed mean and stdev for a user-specified month/year.
Parameters
store Indexed weather data store.
calc Calculator instance.
output OutputHandler instance.
Definition at line 70 of file MenuHandler.cpp.
References Calculator::CalculateWindStats(), OutputHandler::DisplayNoData(), OutputHandler::DisplayWindStats(), GetMonthInput(), and GetYearInput().
Referenced by main().
HandleOption2()
void MenuHandler::HandleOption2 (const WeatherDataStore & store, const Calculator & calc, const OutputHandler & output) const
Option 2 — temperature statistics for all months of a year.
Parameters
store Indexed weather data store.
calc Calculator instance.
output OutputHandler instance.
Definition at line 85 of file MenuHandler.cpp.
References Calculator::CalculateTempStats(), OutputHandler::DisplayNoDataForMonth(), OutputHandler::DisplayTempForMonth(), OutputHandler::DisplayTempHeader(), and GetYearInput().
Referenced by main().
HandleOption3()
void MenuHandler::HandleOption3 (const WeatherDataStore & store, const Calculator & calc, const OutputHandler & output) const
Option 3 — Sample Pearson Correlation Coefficients (S_T, S_R, T_R) for a user-specified month across ALL loaded years.
Parameters
store Indexed weather data store.
calc Calculator instance.
output OutputHandler instance.
Definition at line 102 of file MenuHandler.cpp.
References Calculator::CalculateCorrelations(), OutputHandler::DisplaySPCC(), OutputHandler::DisplaySPCCHeader(), OutputHandler::DisplaySPCCNoData(), and GetMonthInput().
Referenced by main().
HandleOption4()
void MenuHandler::HandleOption4 (const WeatherDataStore & store, const Calculator & calc, const OutputHandler & output) const
Option 4 — write Wind/Temp/Solar CSV with stdev and MAD for a year.
Parameters
store Indexed weather data store.
calc Calculator instance.
output OutputHandler instance.
Definition at line 119 of file MenuHandler.cpp.
References Calculator::CalculateSolarTotal(), Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), OutputHandler::DisplayFileError(), OutputHandler::DisplayFileWritten(), GetYearInput(), OUTPUT_FILENAME, OutputHandler::WriteCSVHeader(), OutputHandler::WriteCSVNoData(), and OutputHandler::WriteCSVRow().
Referenced by main().
PrintYear()
void MenuHandler::PrintYear (int & year) static private
Static visitor passed to Bst<int>::inOrderTraversal as f1Typ.
Signature is void (*)(int&) to match Bst<T>::f1Typ exactly. Must be static so its address is a plain function pointer (not a member pointer), which is what Bst<T>::inOrderTraversal requires. Prints the year value followed by a space.
Parameters
year Year value delivered by the BST traversal.
Definition at line 13 of file MenuHandler.cpp.
Referenced by DisplayAvailableYears().
The documentation for this class was generated from the following files:
MenuHandler.h
MenuHandler.cpp