Assignment2: DataLoader Class Reference
DataLoader Class Reference
#include <DataLoader.h>
Public Member Functions
DataLoader ()
Default constructor.
bool LoadFromFile (const std::string &filename, Vector< WeatherRecord > &records)
Load weather records from a CSV file.
std::string GetLastError () const
Get the most recent error description.
Private Member Functions
bool ParseHeader (const std::string &header, int &wastIdx, int &windIdx, int &solarIdx, int &tempIdx)
Parse the CSV header row to locate column indices.
bool ParseLine (const std::string &line, int wastIdx, int windIdx, int solarIdx, int tempIdx, WeatherRecord &record)
Parse one CSV data line into a WeatherRecord.
bool ParseWAST (const std::string &wast, Date &date, Time &time)
Parse the combined WAST date/time field.
std::string Trim (const std::string &str)
Trim leading and trailing whitespace from a string.
float SafeStringToFloat (const std::string &str, float defaultVal)
Convert a string to float, returning a default on failure.
Private Attributes
std::string m_lastError
Detailed Description
Definition at line 26 of file DataLoader.h.
Constructor & Destructor Documentation
DataLoader()
DataLoader::DataLoader ()
Default constructor.
Definition at line 8 of file DataLoader.cpp.
Member Function Documentation
GetLastError()
std::string DataLoader::GetLastError () const
Get the most recent error description.
Returns
Error message string, or empty string if no error occurred
Definition at line 89 of file DataLoader.cpp.
References m_lastError.
Referenced by DataFileManager::LoadDataFiles(), and test21().
LoadFromFile()
bool DataLoader::LoadFromFile (const std::string & filename, Vector< WeatherRecord > & records)
Load weather records from a CSV file.
Parameters
filename Path to the CSV file
records Vector to append loaded records to
Returns
true if at least one valid record was loaded
Definition at line 12 of file DataLoader.cpp.
References Vector< T >::Append(), m_lastError, ParseHeader(), and ParseLine().
Referenced by DataFileManager::LoadDataFiles(), test16(), test17(), and test21().
ParseHeader()
bool DataLoader::ParseHeader (const std::string & header, int & wastIdx, int & windIdx, int & solarIdx, int & tempIdx) private
Parse the CSV header row to locate column indices.
Parameters
header Header line string
wastIdx Output: WAST column index (-1 if not found)
windIdx Output: S (wind speed) column index
solarIdx Output: SR (solar radiation) column index
tempIdx Output: T (temperature) column index
Returns
true if the mandatory WAST column was found
Definition at line 94 of file DataLoader.cpp.
References Trim().
Referenced by LoadFromFile().
ParseLine()
bool DataLoader::ParseLine (const std::string & line, int wastIdx, int windIdx, int solarIdx, int tempIdx, WeatherRecord & record) private
Parse one CSV data line into a WeatherRecord.
Parameters
line CSV data line
wastIdx WAST column index
windIdx Wind speed column index
solarIdx Solar radiation column index
tempIdx Temperature column index
record Output: populated WeatherRecord
Returns
true if the line was successfully parsed
Definition at line 118 of file DataLoader.cpp.
References MAX_CSV_FIELDS, ParseWAST(), SafeStringToFloat(), WeatherRecord::SetDate(), WeatherRecord::SetSolarRadiation(), WeatherRecord::SetTemperature(), WeatherRecord::SetTime(), WeatherRecord::SetWindSpeed(), and Trim().
Referenced by LoadFromFile().
ParseWAST()
bool DataLoader::ParseWAST (const std::string & wast, Date & date, Time & time) private
Parse the combined WAST date/time field.
Parameters
wast WAST string (format: "DD/MM/YYYY H:MM")
date Output: parsed Date
time Output: parsed Time
Returns
true if successfully parsed
Definition at line 166 of file DataLoader.cpp.
References Date::SetDate(), and Time::SetTime().
Referenced by ParseLine().
SafeStringToFloat()
float DataLoader::SafeStringToFloat (const std::string & str, float defaultVal) private
Convert a string to float, returning a default on failure.
Parameters
str String to convert
defaultVal Value returned if conversion fails
Returns
Converted float or defaultVal
Definition at line 207 of file DataLoader.cpp.
Referenced by ParseLine().
Trim()
std::string DataLoader::Trim (const std::string & str) private
Trim leading and trailing whitespace from a string.
Parameters
str Input string
Returns
Trimmed copy
Definition at line 195 of file DataLoader.cpp.
Referenced by ParseHeader(), and ParseLine().
Member Data Documentation
m_lastError
std::string DataLoader::m_lastError private
Most recent error description
Definition at line 50 of file DataLoader.h.
Referenced by GetLastError(), and LoadFromFile().
The documentation for this class was generated from the following files:
DataLoader.h
DataLoader.cpp