Assignment2: DataFileManager Class Reference
DataFileManager Class Reference
#include <DataFileManager.h>
Public Member Functions
DataFileManager ()
Default constructor — initialises all counters to zero.
int ReadDataSourceFile (const std::string &dataSourceFile, Vector< std::string > &filenames)
Read CSV filenames from a data-source configuration file.
int LoadDataFiles (const Vector< std::string > &filenames, Vector< WeatherRecord > &records, DataLoader &loader, const std::string &dataPath)
Load weather records from each CSV file in the list.
int GetFilesLoaded () const
Number of files successfully loaded.
int GetDuplicateCount () const
Number of duplicate records that were filtered out.
int GetFileCount () const
Total number of files that were attempted.
std::string GetFileResult (int index) const
Retrieve the result string for one file.
Private Member Functions
bool IsDuplicateRecord (const Vector< WeatherRecord > &records, const WeatherRecord &newRecord) const
Check whether a record's timestamp already exists in the BST.
long long MakeTimestampKey (const WeatherRecord &record) const
Build a compact 64-bit integer key from a record's timestamp.
Private Attributes
int m_filesLoaded
int m_duplicateCount
int m_fileCount
std::string m_fileResults [MAX_FILE_RESULTS]
Bst< long long > m_timestampBst
Bst<long long> used for O(log n) duplicate-timestamp detection.
Static Private Attributes
static const int MAX_FILE_RESULTS = 100
Maximum number of files that can be tracked.
Detailed Description
Definition at line 31 of file DataFileManager.h.
Constructor & Destructor Documentation
DataFileManager()
DataFileManager::DataFileManager ()
Default constructor — initialises all counters to zero.
Definition at line 7 of file DataFileManager.cpp.
Member Function Documentation
GetDuplicateCount()
int DataFileManager::GetDuplicateCount () const
Number of duplicate records that were filtered out.
Definition at line 110 of file DataFileManager.cpp.
References m_duplicateCount.
Referenced by main(), test1(), test18(), and test19().
GetFileCount()
int DataFileManager::GetFileCount () const
Total number of files that were attempted.
Definition at line 115 of file DataFileManager.cpp.
References m_fileCount.
Referenced by main().
GetFileResult()
std::string DataFileManager::GetFileResult (int index) const
Retrieve the result string for one file.
Parameters
index Zero-based file index (must be < GetFileCount()).
Returns
Result string, or empty string if index is out of range.
Definition at line 120 of file DataFileManager.cpp.
References m_fileCount, and m_fileResults.
Referenced by main().
GetFilesLoaded()
int DataFileManager::GetFilesLoaded () const
Number of files successfully loaded.
Definition at line 105 of file DataFileManager.cpp.
References m_filesLoaded.
Referenced by main(), and test1().
IsDuplicateRecord()
bool DataFileManager::IsDuplicateRecord (const Vector< WeatherRecord > & records, const WeatherRecord & newRecord) const private
Check whether a record's timestamp already exists in the BST.
Parameters
records Unused parameter (kept for interface compatibility).
newRecord Record to check for duplication.
Returns
true if a duplicate key is found in m_timestampBst.
Definition at line 126 of file DataFileManager.cpp.
References m_timestampBst, MakeTimestampKey(), and Bst< T >::search().
Referenced by LoadDataFiles().
LoadDataFiles()
int DataFileManager::LoadDataFiles (const Vector< std::string > & filenames, Vector< WeatherRecord > & records, DataLoader & loader, const std::string & dataPath)
Load weather records from each CSV file in the list.
Iterates through filenames, loads each via DataLoader, then inserts each new record's timestamp key into the duplicate-detection BST. Records whose key is already present in the BST are skipped.
Parameters
filenames Vector of bare filenames (without directory prefix).
records Vector to append loaded records to.
loader DataLoader instance used for each file.
dataPath Directory prefix prepended to each filename.
Returns
Total number of unique records loaded across all files.
Definition at line 45 of file DataFileManager.cpp.
References Vector< T >::Append(), DataLoader::GetLastError(), Bst< T >::insert(), IsDuplicateRecord(), DataLoader::LoadFromFile(), m_duplicateCount, m_fileCount, m_fileResults, m_filesLoaded, m_timestampBst, MakeTimestampKey(), MAX_FILE_RESULTS, and Vector< T >::Size().
Referenced by main(), test1(), test18(), and test19().
MakeTimestampKey()
long long DataFileManager::MakeTimestampKey (const WeatherRecord & record) const private
Build a compact 64-bit integer key from a record's timestamp.
Encoding: key = year * 100,000,000
month * 1,000,000
day * 10,000
hour * 100
minute
This encoding is unique for any valid (year, month, day, hour, minute) combination within the weather data range. It avoids dynamic string allocation, keeping per-record overhead minimal.
Parameters
record WeatherRecord whose date/time components are encoded.
Returns
Integer key unique for each distinct date+time pair.
Definition at line 133 of file DataFileManager.cpp.
References WeatherRecord::GetDate(), Date::GetDay(), Time::GetHour(), Time::GetMinute(), Date::GetMonth(), WeatherRecord::GetTime(), and Date::GetYear().
Referenced by IsDuplicateRecord(), and LoadDataFiles().
ReadDataSourceFile()
int DataFileManager::ReadDataSourceFile (const std::string & dataSourceFile, Vector< std::string > & filenames)
Read CSV filenames from a data-source configuration file.
Parameters
dataSourceFile Full path to the configuration file.
filenames Vector to append filenames to.
Returns
Number of filenames read, or 0 on error.
Definition at line 13 of file DataFileManager.cpp.
References Vector< T >::Append().
Referenced by main(), and test22().
Member Data Documentation
m_duplicateCount
int DataFileManager::m_duplicateCount private
Duplicate records filtered.
Definition at line 84 of file DataFileManager.h.
Referenced by GetDuplicateCount(), and LoadDataFiles().
m_fileCount
int DataFileManager::m_fileCount private
Total files attempted.
Definition at line 85 of file DataFileManager.h.
Referenced by GetFileCount(), GetFileResult(), and LoadDataFiles().
m_fileResults
std::string DataFileManager::m_fileResults[MAX_FILE_RESULTS] private
Per-file result strings.
Definition at line 90 of file DataFileManager.h.
Referenced by GetFileResult(), and LoadDataFiles().
m_filesLoaded
int DataFileManager::m_filesLoaded private
Files successfully loaded.
Definition at line 83 of file DataFileManager.h.
Referenced by GetFilesLoaded(), and LoadDataFiles().
m_timestampBst
Bst<long long> DataFileManager::m_timestampBst private
Bst<long long> used for O(log n) duplicate-timestamp detection.
Each record's date and time are encoded into a single 64-bit integer key (see MakeTimestampKey). The BST rejects duplicate key insertions automatically, making search() a clean O(log n) existence check.
Using Bst<long long> here provides a second concrete use of the BST beyond the year index.
Definition at line 102 of file DataFileManager.h.
Referenced by IsDuplicateRecord(), and LoadDataFiles().
MAX_FILE_RESULTS
const int DataFileManager::MAX_FILE_RESULTS = 100 static private
Maximum number of files that can be tracked.
Definition at line 88 of file DataFileManager.h.
Referenced by LoadDataFiles().
The documentation for this class was generated from the following files:
DataFileManager.h
DataFileManager.cpp