Assignment2: MapTest.cpp File Reference
MapTest.cpp File Reference
Unit tests for Map<K,V> — Test Plan tests 1-10.
#include <iostream>
#include <string>
#include "Map.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
static void test9 ()
static void test10 ()
int main ()
Variables
static int passed = 0
static int failed = 0
Detailed Description
Unit tests for Map<K,V> — Test Plan tests 1-10.
Tests cover all four public methods of Map (version 2.0): operator[] — insert-or-access getPtr() — safe read; nullptr for absent key size() — entry count; size()==0 replaces the old isEmpty() getKey(i) — key at index; combined with getPtr replaces old getValue(i)
Previously tested methods that have been removed in version 2.0: contains() — replaced by getPtr(key) != nullptr isEmpty() — replaced by size() == 0 remove() — never called in the application; removed from interface getValue(i) — replaced by getPtr(getKey(i))
Author
Deston
Date
25/03/2026
Definition in file MapTest.cpp.
Function Documentation
main()
int main ()
Definition at line 199 of file MapTest.cpp.
References failed, passed, test1(), test10(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 28 of file MapTest.cpp.
References failed, and passed.
Referenced by test1(), test10(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
test1()
static void test1 () static
Definition at line 40 of file MapTest.cpp.
References Map< K, V >::getPtr(), report(), and Map< K, V >::size().
Referenced by main().
test10()
static void test10 () static
Definition at line 179 of file MapTest.cpp.
References Map< K, V >::getPtr(), and report().
Referenced by main().
test2()
static void test2 () static
Definition at line 51 of file MapTest.cpp.
References Map< K, V >::getPtr(), report(), and Map< K, V >::size().
Referenced by main().
test3()
static void test3 () static
Definition at line 66 of file MapTest.cpp.
References report(), and Map< K, V >::size().
Referenced by main().
test4()
static void test4 () static
Definition at line 81 of file MapTest.cpp.
References Map< K, V >::getPtr(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 92 of file MapTest.cpp.
References Map< K, V >::getPtr(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 104 of file MapTest.cpp.
References Map< K, V >::getPtr(), and report().
Referenced by main().
test7()
static void test7 () static
Definition at line 116 of file MapTest.cpp.
References report(), and Map< K, V >::size().
Referenced by main().
test8()
static void test8 () static
Definition at line 133 of file MapTest.cpp.
References Map< K, V >::getKey(), report(), and Map< K, V >::size().
Referenced by main().
test9()
static void test9 () static
Definition at line 152 of file MapTest.cpp.
References Map< K, V >::getKey(), Map< K, V >::getPtr(), report(), and Map< K, V >::size().
Referenced by main().
Variable Documentation
failed
int failed = 0 static
Definition at line 26 of file MapTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 25 of file MapTest.cpp.
Referenced by main(), and report().