Assignment2: MenuHandlerTest.cpp File Reference
MenuHandlerTest.cpp File Reference
Unit tests for MenuHandler (Assignment 2) — Test Plan tests 1-7.
#include <iostream>
#include <sstream>
#include <string>
#include "MenuHandler.h"
#include "WeatherDataStore.h"
#include "WeatherRecord.h"
#include "Date.h"
#include "Time.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static bool contains (const std::string &haystack, const std::string &needle)
static WeatherDataStore buildStoreWithYears (int *years, int n)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
int main ()
Variables
static int passed = 0
static int failed = 0
Detailed Description
Unit tests for MenuHandler (Assignment 2) — Test Plan tests 1-7.
Strategy: redirect std::cout to a std::ostringstream before each call and inspect the captured string. Stdin-dependent methods (DisplayMenu, GetYearInput, GetMonthInput) are NOT tested here — they require interactive input and belong in an integration/acceptance test.
Tests cover:
DisplayWelcome output contains record count.
DisplayGoodbye output contains expected exit text.
DisplayAvailableYears uses BST in-order traversal (sorted years).
DisplayAvailableYears with a single year.
PrintYear static callback prints value followed by space.
DisplayMenu output lists all five options.
DisplayAvailableYears years printed in ascending order for data inserted out of order (confirms BST sorting, not insertion order).
Note: DisplayMenu reads from cin; the test only verifies that the output text is correct by examining the prompt text without supplying input. Prompt string is tested only, not the return value, to avoid blocking.
Author
Deston
Date
24/03/2026
Definition in file MenuHandlerTest.cpp.
Function Documentation
buildStoreWithYears()
static WeatherDataStore buildStoreWithYears (int * years, int n) static
Definition at line 53 of file MenuHandlerTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherRecord::SetDate(), WeatherRecord::SetSolarRadiation(), WeatherRecord::SetTemperature(), WeatherRecord::SetTime(), and WeatherRecord::SetWindSpeed().
Referenced by test3(), test4(), test5(), and test7().
contains()
static bool contains (const std::string & haystack, const std::string & needle) static
Definition at line 47 of file MenuHandlerTest.cpp.
Referenced by test1(), test2(), test3(), test4(), test5(), and test6().
main()
int main ()
Definition at line 223 of file MenuHandlerTest.cpp.
References failed, passed, test1(), test2(), test3(), test4(), test5(), test6(), and test7().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 40 of file MenuHandlerTest.cpp.
References failed, and passed.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), and test7().
test1()
static void test1 () static
Definition at line 72 of file MenuHandlerTest.cpp.
References contains(), MenuHandler::DisplayWelcome(), and report().
Referenced by main().
test2()
static void test2 () static
Definition at line 85 of file MenuHandlerTest.cpp.
References contains(), MenuHandler::DisplayGoodbye(), and report().
Referenced by main().
test3()
static void test3 () static
Definition at line 103 of file MenuHandlerTest.cpp.
References buildStoreWithYears(), contains(), MenuHandler::DisplayAvailableYears(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 131 of file MenuHandlerTest.cpp.
References buildStoreWithYears(), contains(), MenuHandler::DisplayAvailableYears(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 150 of file MenuHandlerTest.cpp.
References buildStoreWithYears(), contains(), MenuHandler::DisplayAvailableYears(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 170 of file MenuHandlerTest.cpp.
References contains(), MenuHandler::DisplayMenu(), and report().
Referenced by main().
test7()
static void test7 () static
Definition at line 196 of file MenuHandlerTest.cpp.
References buildStoreWithYears(), MenuHandler::DisplayAvailableYears(), and report().
Referenced by main().
Variable Documentation
failed
int failed = 0 static
Definition at line 38 of file MenuHandlerTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 37 of file MenuHandlerTest.cpp.
Referenced by main(), and report().