Assignment2: OutputHandlerTest.cpp File Reference
OutputHandlerTest.cpp File Reference
Unit tests for OutputHandler (Assignment 2) — Test Plan tests 1-12.
#include <iostream>
#include <sstream>
#include <string>
#include <fstream>
#include <cmath>
#include "OutputHandler.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static std::string capture (void(*fn)(const OutputHandler &), const OutputHandler &o)
static bool contains (const std::string &haystack, const std::string &needle)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
static void test9 ()
static void test10 ()
static void test11 ()
static void test12 ()
int main ()
Variables
static int passed = 0
static int failed = 0
Detailed Description
Unit tests for OutputHandler (Assignment 2) — Test Plan tests 1-12.
Strategy: redirect std::cout to a std::ostringstream before each call and inspect the captured string. CSV methods write to a temporary std::ostringstream-backed stream so no real files are created.
Tests cover all Assignment 2 methods: DisplaySPCCHeader, DisplaySPCC, DisplaySPCCNoData, WriteCSVRow with stdev+MAD, WriteCSVNoData, and the existing option-1/2/4 methods to confirm they still produce correct output.
Manual verification of expected strings: DisplayWindStats(3, 2020, 5.4, 2.5): "March 2020:", "Average speed: 5.4 km/h", "Sample stdev: 2.5"
DisplayTempForMonth(1, 15.0, 7.1): "January: average: 15.0 degrees C, stdev: 7.1"
DisplaySPCC(0.85, -0.12, 0.67): "S_T: 0.85", "S_R: -0.12", "T_R: 0.67" (2 d.p.)
WriteCSVRow month=5 (May), hasWind=true wind=3.6/0.0/0.0, hasTemp=true temp=20.0/0.0/0.0, hasSolar=true solar=0.1: "May, 3.6(0.0, 0.0),20.0(0.0, 0.0),0.1"
Author
Deston
Date
24/03/2026
Definition in file OutputHandlerTest.cpp.
Function Documentation
capture()
static std::string capture (void(*)(const OutputHandler &) fn, const OutputHandler & o) static
Redirect cout -> oss, call fn(), restore cout, return captured string.
Definition at line 51 of file OutputHandlerTest.cpp.
contains()
static bool contains (const std::string & haystack, const std::string & needle) static
Definition at line 60 of file OutputHandlerTest.cpp.
Referenced by test1(), test10(), test11(), test12(), test2(), test3(), test4(), test5(), test6(), test7(), and test8().
main()
int main ()
Definition at line 287 of file OutputHandlerTest.cpp.
References failed, passed, test1(), test10(), test11(), test12(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 43 of file OutputHandlerTest.cpp.
References failed, and passed.
Referenced by test1(), test10(), test11(), test12(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
test1()
static void test1 () static
Definition at line 68 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplayWindStats(), and report().
Referenced by main().
test10()
static void test10 () static
Definition at line 220 of file OutputHandlerTest.cpp.
References contains(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVRow().
Referenced by main().
test11()
static void test11 () static
Definition at line 246 of file OutputHandlerTest.cpp.
References contains(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVRow().
Referenced by main().
test12()
static void test12 () static
Definition at line 270 of file OutputHandlerTest.cpp.
References contains(), report(), OutputHandler::WriteCSVHeader(), and OutputHandler::WriteCSVNoData().
Referenced by main().
test2()
static void test2 () static
Definition at line 86 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplayNoData(), and report().
Referenced by main().
test3()
static void test3 () static
Definition at line 102 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplayTempHeader(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 116 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplayTempForMonth(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 133 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplayNoDataForMonth(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 147 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplaySPCCHeader(), and report().
Referenced by main().
test7()
static void test7 () static
Definition at line 163 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplaySPCC(), and report().
Referenced by main().
test8()
static void test8 () static
Definition at line 182 of file OutputHandlerTest.cpp.
References contains(), OutputHandler::DisplaySPCCNoData(), and report().
Referenced by main().
test9()
static void test9 () static
Definition at line 196 of file OutputHandlerTest.cpp.
References report(), and OutputHandler::WriteCSVHeader().
Referenced by main().
Variable Documentation
failed
int failed = 0 static
Definition at line 39 of file OutputHandlerTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 38 of file OutputHandlerTest.cpp.
Referenced by main(), and report().