Assignment2: StatsTest.cpp File Reference
StatsTest.cpp File Reference
Unit tests for Stats free functions — Test Plan tests 1-11.
#include <iostream>
#include <string>
#include <cmath>
#include "Stats.h"
#include "Vector.h"
Functions
static bool approx (float a, float b)
static void report (int testNum, const std::string &desc, bool ok)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
static void test9 ()
static void test10 ()
static void test11 ()
int main ()
Variables
static int passed = 0
static int failed = 0
static const float EPSILON = 0.001f
Detailed Description
Unit tests for Stats free functions — Test Plan tests 1-11.
Tests cover: CalculateMean, CalculateSampleStdDev, CalculateMAD, CalculateSPCC edge cases (n<2, mismatched size, perfect +/- correlation).
Manual verification of all expected values:
CalculateMean({2,4,6}) = 12/3 = 4.0
CalculateSampleStdDev({2,4,6}, mean=4): sum_sq_diffs = (2-4)^2 + (4-4)^2 + (6-4)^2 = 4+0+4 = 8 sample variance = 8 / (3-1) = 8/2 = 4.0 stdev = sqrt(4) = 2.0 <– NOTE: NOT 2.828 2.828 = sqrt(8) which is wrong (omits the /2 denominator)
CalculateMAD({1,3,5}, mean=3): MAD = (|1-3| + |3-3| + |5-3|) / 3 = (2+0+2)/3 = 4/3 = 1.333
CalculateSPCC perfect positive {x=y}: num = sum((xi-mx)(yi-my)) = sum((xi-mx)^2) -> denom = dX = dY result = 1.0
CalculateSPCC perfect negative {x={1,2,3}, y={3,2,1}}: mx=2, my=2; num = (-1)(1)+(0)(0)+(1)(-1) = -2 dX=2, dY=2, denom=2; spcc = -2/2 = -1.0
Author
Deston
Date
24/03/2026
Definition in file StatsTest.cpp.
Function Documentation
approx()
static bool approx (float a, float b) static
Definition at line 44 of file StatsTest.cpp.
References EPSILON.
Referenced by test1(), test10(), test11(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
main()
int main ()
Definition at line 164 of file StatsTest.cpp.
References failed, passed, test1(), test10(), test11(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 49 of file StatsTest.cpp.
References failed, and passed.
Referenced by test1(), test10(), test11(), test2(), test3(), test4(), test5(), test6(), test7(), test8(), and test9().
test1()
static void test1 () static
Definition at line 57 of file StatsTest.cpp.
References approx(), CalculateMean(), and report().
Referenced by main().
test10()
static void test10 () static
Definition at line 146 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSPCC(), and report().
Referenced by main().
test11()
static void test11 () static
Definition at line 155 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSPCC(), and report().
Referenced by main().
test2()
static void test2 () static
Definition at line 65 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateMean(), and report().
Referenced by main().
test3()
static void test3 () static
Definition at line 73 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateMean(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 82 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSampleStdDev(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 93 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSampleStdDev(), and report().
Referenced by main().
test6()
static void test6 () static
Definition at line 103 of file StatsTest.cpp.
References approx(), CalculateMAD(), and report().
Referenced by main().
test7()
static void test7 () static
Definition at line 112 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateMAD(), and report().
Referenced by main().
test8()
static void test8 () static
Definition at line 123 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSPCC(), and report().
Referenced by main().
test9()
static void test9 () static
Definition at line 136 of file StatsTest.cpp.
References Vector< T >::Append(), approx(), CalculateSPCC(), and report().
Referenced by main().
Variable Documentation
EPSILON
const float EPSILON = 0.001f static
Definition at line 42 of file StatsTest.cpp.
Referenced by approx().
failed
int failed = 0 static
Definition at line 40 of file StatsTest.cpp.
Referenced by main(), and report().
passed
int passed = 0 static
Definition at line 39 of file StatsTest.cpp.
Referenced by main(), and report().