Assignment2: Stats.h File Reference
Stats.h File Reference
Generic statistical free functions for float vectors.
#include "Vector.h"
Functions
float CalculateMean (const Vector< float > &data)
Calculate the arithmetic mean.
float CalculateSampleStdDev (const Vector< float > &data, float mean)
Calculate the sample standard deviation.
float CalculateMAD (const Vector< float > &data, float mean)
Calculate the Mean Absolute Deviation.
float CalculateSPCC (const Vector< float > &x, const Vector< float > &y)
Calculate the Sample Pearson Correlation Coefficient.
Detailed Description
Generic statistical free functions for float vectors.
Provides mean, sample standard deviation, mean absolute deviation, and sample Pearson correlation coefficient. No dependency on any weather-domain type.
Author
Deston
Version
2.0
Date
24/03/2026
Definition in file Stats.h.
Function Documentation
CalculateMAD()
float CalculateMAD (const Vector< float > & data, float mean)
Calculate the Mean Absolute Deviation.
Parameters
data Vector of float values.
mean Pre-calculated mean.
Returns
MAD, or 0.0 if empty.
Definition at line 25 of file Stats.cpp.
References Vector< T >::Size().
Referenced by Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), test6(), and test7().
CalculateMean()
float CalculateMean (const Vector< float > & data)
Calculate the arithmetic mean.
Parameters
data Vector of float values.
Returns
Mean, or 0.0 if empty.
Definition at line 5 of file Stats.cpp.
References Vector< T >::Size().
Referenced by CalculateSPCC(), Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), test1(), test2(), and test3().
CalculateSampleStdDev()
float CalculateSampleStdDev (const Vector< float > & data, float mean)
Calculate the sample standard deviation.
Parameters
data Vector of float values.
mean Pre-calculated mean.
Returns
Sample stdev (n-1 denominator), or 0.0 if size <= 1.
Definition at line 13 of file Stats.cpp.
References Vector< T >::Size().
Referenced by Calculator::CalculateTempStats(), Calculator::CalculateWindStats(), test4(), and test5().
CalculateSPCC()
float CalculateSPCC (const Vector< float > & x, const Vector< float > & y)
Calculate the Sample Pearson Correlation Coefficient.
Parameters
x First variable (must be same size as y).
y Second variable.
Returns
sPCC in [-1, 1], or 0.0 if n < 2 or denominator is 0.
Definition at line 34 of file Stats.cpp.
References CalculateMean(), and Vector< T >::Size().
Referenced by Calculator::CalculateCorrelations(), test10(), test11(), test8(), and test9().