Assignment2: WeatherDataStoreTest.cpp File Reference
WeatherDataStoreTest.cpp File Reference
Unit tests for WeatherDataStore — Test Plan tests 1-8.
#include <iostream>
#include <string>
#include "WeatherDataStore.h"
#include "WeatherRecord.h"
#include "Date.h"
#include "Time.h"
#include "Vector.h"
Functions
static void report (int testNum, const std::string &desc, bool ok)
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp)
static void collectYear (int &yr)
static void test1 ()
static void test2 ()
static void test3 ()
static void test4 ()
static void test5 ()
static void test6 ()
static void test7 ()
static void test8 ()
int main ()
Variables
static int passed = 0
static int failed = 0
static const float EPSILON = 0.001f
static Vector< int > g_years
Detailed Description
Unit tests for WeatherDataStore — Test Plan tests 1-8.
Tests cover: Build from empty, year BST insert, HasData, GetMonthData, GetMonthDataAllYears, TraverseYears (function pointer), YearExists, and wind speed km/h conversion on insert.
Author
Deston
Date
24/03/2026
Definition in file WeatherDataStoreTest.cpp.
Function Documentation
collectYear()
static void collectYear (int & yr) static
Definition at line 49 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), and g_years.
Referenced by test7().
main()
int main ()
Definition at line 152 of file WeatherDataStoreTest.cpp.
References failed, passed, test1(), test2(), test3(), test4(), test5(), test6(), test7(), and test8().
makeRecord()
static WeatherRecord makeRecord (int day, int month, int year, float windMps, float solar, float temp) static
Definition at line 33 of file WeatherDataStoreTest.cpp.
References WeatherRecord::SetDate(), WeatherRecord::SetSolarRadiation(), WeatherRecord::SetTemperature(), WeatherRecord::SetTime(), and WeatherRecord::SetWindSpeed().
Referenced by test2(), test3(), test4(), test5(), test6(), test7(), and test8().
report()
static void report (int testNum, const std::string & desc, bool ok) static
Definition at line 25 of file WeatherDataStoreTest.cpp.
References failed, and passed.
Referenced by test1(), test2(), test3(), test4(), test5(), test6(), test7(), and test8().
test1()
static void test1 () static
Definition at line 52 of file WeatherDataStoreTest.cpp.
References WeatherDataStore::Build(), WeatherDataStore::IsEmpty(), and report().
Referenced by main().
test2()
static void test2 () static
Definition at line 61 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherDataStore::GetYearCount(), makeRecord(), report(), and WeatherDataStore::YearExists().
Referenced by main().
test3()
static void test3 () static
Definition at line 72 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherDataStore::HasData(), makeRecord(), and report().
Referenced by main().
test4()
static void test4 () static
Definition at line 82 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherDataStore::HasData(), makeRecord(), and report().
Referenced by main().
test5()
static void test5 () static
Definition at line 92 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherDataStore::GetMonthData(), makeRecord(), report(), Vector< T >::Size(), and MonthlyData::windSpeeds.
Referenced by main().
test6()
static void test6 () static
Definition at line 105 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), WeatherDataStore::GetMonthDataAllYears(), makeRecord(), report(), and Vector< T >::Size().
Referenced by main().
test7()
static void test7 () static
Definition at line 119 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), Vector< T >::Clear(), collectYear(), g_years, makeRecord(), report(), Vector< T >::Size(), and WeatherDataStore::TraverseYears().
Referenced by main().
test8()
static void test8 () static
Definition at line 139 of file WeatherDataStoreTest.cpp.
References Vector< T >::Append(), WeatherDataStore::Build(), EPSILON, WeatherDataStore::GetMonthData(), makeRecord(), report(), and MonthlyData::windSpeeds.
Referenced by main().
Variable Documentation
EPSILON
const float EPSILON = 0.001f static
Definition at line 23 of file WeatherDataStoreTest.cpp.
Referenced by test8().
failed
int failed = 0 static
Definition at line 22 of file WeatherDataStoreTest.cpp.
Referenced by main(), and report().
g_years
Vector<int> g_years static
Definition at line 48 of file WeatherDataStoreTest.cpp.
Referenced by collectYear(), and test7().
passed
int passed = 0 static
Definition at line 21 of file WeatherDataStoreTest.cpp.
Referenced by main(), and report().